# Generated by Django 5.2 on 2025-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фамилия', models.CharField(max_length=100)),
                ('имя', models.CharField(max_length=100)),
                ('отчество', models.CharField(max_length=100)),
                ('телефон', models.CharField(max_length=20)),
                ('почта', models.EmailField(max_length=254)),
                ('кабинет', models.IntegerField()),
                ('статус_кабинета', models.CharField(max_length=50)),
                ('должность', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
